#spring:
#  application:
#    name: security-security
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    driverClassName: oracle.jdbc.OracleDriver
#    username: system
#    password: admin123
#token:
#  signing:
#    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855