server:
  port: 8010
  compression:
    enabled: true
    min-response-size: 128
---
jwt:
  secret: "1j4u3d8nib4a1e4f05c8a0b3f267d8b1d4E6f3c8a9d2b5f8e3a9c8b5f6v8a3d9"
  expiration: 86400000  # Token expiration time in milliseconds (e.g., 24 hours)
---
spring:
  jmx:
    enabled: false
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: jdbc:oracle:thin:@localhost:1521/xe
    username: system
    password: admin123
    pool-size: 30
    hikari:
      connection-timeout: 30000
      idleTimeout: 30000
      minimum-idle: 5
      pool-name: ForumPool
      leak-detection-threshold: 600000
---
logging:
  level:
    org.springframework.security: info
    org.springframework.web: info
    com.zaxxer.hikari.HikariConfig: info
    com.zaxxer.hikari.HikariDataSource: debug
